trigger:
- master

pool: JpMaquina

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run test-ci
    nnpm run build
  displayName: 'npm install, test and build'
  
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'jprogarcia'
    scannerMode: 'CLI'
    configMode: 'file' 
  displayName: 'run SonarCloud'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'